web_address: 0.0.0.0:8080
api_address: 0.0.0.0:9090

routes:
  - path: /form
    component: /layout
    children:
      - path: index
        component: /views/form/index
        meta: {title: Form, icon: form}
  - path: /nform
    component: /layout
    children:
      - path: index
        component: /unknown/path
        meta: {title: 未知页面, icon: form}