web_address: 0.0.0.0:8080
api_address: 0.0.0.0:9090

routes:
  - path: /401
    component: /layout
    children:
      - path: index
        component: /views/401/index
        meta: {title: 401, icon: 401}
  - path: /nform
    component: /layout
    children:
      - path: index
        component: /unknown/path
        meta: {title: 未知页面, icon: form}